spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"

security:
  redirect:
    web: http://localhost:3000

debug: true
logging:
  level:
    org:
      springframework:
        security: TRACE
