### Check root endpoint
GET {{dictionary-server-host}}/

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Add user learningItem
POST {{dictionary-server-host}}/api/languages/en/learning-items
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "text": "test",
  "translation": "тест"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.global.set("created-learningItem-id", response.body.id);
%}

### Get user learning items
GET {{dictionary-server-host}}/api/languages/en/learning-items
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.learningItems.length > 0, "Response should contain learningItems");
    });
%}


### Delete use learningItem
DELETE {{dictionary-server-host}}/api/languages/en/learning-items/{{created-learningItem-id}}
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

