name: Build && Deploy

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Build server
        run: |
          cd dictionary-server
          ./gradlew build

      - name: Increment version
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        run: |
          cd dictionary-server
          ./gradlew currentVersion
          ./gradlew release

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          directory: ./dictionary-server/build/reports/jacoco/test

      - name: Set up QEMU
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        run: |
          cd dictionary-server
          ./gradlew bootBuildImage

      - name: Push Docker image
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        run: |
          docker push --all-tags solomkinmv/dictionary

      - uses: superfly/flyctl-actions/setup-flyctl@master
        if: "!contains(github.event.head_commit.message, '[skip release]')"

      - name: Trigger deploy
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        run: |
          cd dictionary-server
          flyctl deploy --remote-only
