name: Build && Deploy

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: dictionary-client/package-lock.json

      - name: Build client
        run: |
          cd dictionary-client
          npm install
          npm run build

      - name: Build server
        run: |
          cd dictionary-server
          ./gradlew build

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./dictionary-server/build/jacoco/test.exec

      - name: Release new version
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        uses: ./.github/workflows/release.yml
