name: Release new version

on:
  workflow_call:
  workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Copy client to backend resources
        run: |
          cd dictionary-client
          rm -rf ../dictionary-server/src/main/resources/public/static/
          \cp -r ./build/* ../dictionary-server/src/main/resources/public/

      - name: Build Docker image
        if: "!contains(github.event.head_commit.message, '[skip release]')"
        run: |
          cd dictionary-server
          ./gradlew bootBuildImage --imageName=solomkinmv/dictionary:latest

      - name: Push Docker image
        run: |
          docker push solomkinmv/dictionary:latest

      - name: Increment version
        run: |
          cd dictionary-server
          ./gradlew currentVersion
          ./gradlew release -Prelease.disableUncommittedCheck

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: |
          cd dictionary-server
          flyctl deploy --remote-only
